radix-ui/themes

packages/radix-ui-themes/src/components/scroll-area.css

This is currently a little overzealous, creating issues with overlapping elements or text selections within blocks:
https://github.com/radix-ui/themes/assets/11708259/ab9372c6-d0d5-4f2e-9f3e-c8e4036a5b98

[ScrollArea] Reduce thumb tap target size

---

packages/radix-ui-themes/src/components/context-menu.tsx
packages/radix-ui-themes/src/components/dialog.tsx
packages/radix-ui-themes/src/components/dropdown-menu.tsx
packages/radix-ui-themes/src/components/hover-card.tsx
packages/radix-ui-themes/src/components/popover.tsx

Use explicit React.FC type for components that don’t forward refs

Use explicit React.FC type

---

packages/radix-ui-themes/changelog.md
packages/radix-ui-themes/package.json
packages/radix-ui-themes/postcss-radix-themes.js
packages/radix-ui-themes/postcss.config.js
yarn.lock

- Combine duplicate CSS selectors to improve the developer experience when inspecting Radix Themes elements
- Remove comments from the CSS build
Before:
https://github.com/radix-ui/themes/assets/8441036/d124f12f-1fce-4e44-a38d-249573563a33
After:
https://github.com/radix-ui/themes/assets/8441036/25997e8c-6101-4c8d-a609-e6ce61734302
Build diff:
https://www.diffchecker.com/hY0sDxP9/

Combine duplicate CSS selectors

---

packages/radix-ui-themes/changelog.md
packages/radix-ui-themes/src/styles/tokens/color.css

Fixes an issue when an input within a forced dark/light appearance section would not used the appropriate autofill background color, as the browser wouldn't know that the color scheme was changed in the section

Set color scheme with forced light/dark appearance

---

packages/radix-ui-themes/changelog.md
packages/radix-ui-themes/src/components/base-button.css
packages/radix-ui-themes/src/components/card.css
packages/radix-ui-themes/src/components/checkbox.css
packages/radix-ui-themes/src/components/radio-group.css
packages/radix-ui-themes/src/components/scroll-area.css
packages/radix-ui-themes/src/components/select.css
packages/radix-ui-themes/src/components/switch.css
packages/radix-ui-themes/src/components/tabs.css
packages/radix-ui-themes/src/components/text-area.css
packages/radix-ui-themes/src/components/text-field.css

Fixes janky focus outline anti-aliasing in Chrome
***
Before/after, light mode
***
Before/after, dark mode

Better focus outlines

---

apps/playground/app/sink/page.tsx
packages/radix-ui-themes/src/components/grid.css
packages/radix-ui-themes/src/components/grid.tsx

Example layout, before:
This is incorrect—first and last child grid inherit parent grid columns, instead of using own values.
Example layout, after:
***
Inspecting a child element, before:
Inspecting a child element, after:

Fix nested Grid values inheritance

---

packages/radix-ui-themes/package.json

Add `style` so that apps with `postcss-import` can import Radix Themes stylesheet by `@import "@radix-ui/themes";`

Support `postcss-import`

---

packages/radix-ui-themes/src/components/base-button.css
packages/radix-ui-themes/src/components/card.css
packages/radix-ui-themes/src/components/kbd.css
packages/radix-ui-themes/src/components/select.css
packages/radix-ui-themes/src/components/slider.css
packages/radix-ui-themes/src/components/switch.css
packages/radix-ui-themes/src/styles/tokens/color.css
packages/radix-ui-themes/src/styles/tokens/shadow.css

After merging all the todays PR's, the order of rules in the built CSS got messed up somehow and broke dark mode, although previews on each PR individually looked correct.
Broken dark mode:

Fix CSS rule order

---

packages/radix-ui-themes/src/components/base-button.tsx

Explicit `<Button disabled={false} />` yielded a button that looked disabled

Fix disabled buttons

---

packages/radix-ui-themes/src/components/card.css
packages/radix-ui-themes/src/styles/tokens/color.css
packages/radix-ui-themes/src/styles/tokens/shadow.css

- Desaturate light mode shadows and overlays for a more natural look
- Fix `--color-transparent` sRGB variant taking over the P3 variant, which yielded that Chrome's bug with transition through red on box shadows

Update shadows and overlays

---

packages/radix-ui-themes/package.json

I attempted to import the @radix-ui/themes/styles.css file into my SCSS module, but I encountered an error regarding export limitations. The error message looked like this:
```plain
error[internal]: Package path @radix-ui/themes/styles.css is not exported in <REPOSITORY>/node_modules/@radix-ui/themes/package.json
```
It appears that the css-loader only recognizes the `default` export and ignores the `import` and `require` fields. To resolve this issue, I added a default export, and it resolved the problem.

fix: css-loader can't resolve `@radix-ui/themes/styles.css`

---

packages/radix-ui-themes/changelog.md
packages/radix-ui-themes/package.json
packages/radix-ui-themes/src/components/text-area.css

Fixes a bugged CSS selector that caused Chrome crashes when interacting with CSS inspector.

Fix bugged Text Area selector (2.0.2)

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
README.md

This PR adds contributor docs using the primitives docs as a starting point. Also adds code of conduct and PR template.

Add contributor docs

---

apps/playground/app/sink/page.tsx
packages/radix-ui-themes/changelog.md
packages/radix-ui-themes/src/components/tabs.css
packages/radix-ui-themes/src/components/tabs.props.ts
packages/radix-ui-themes/src/components/tabs.tsx

Support the `color` prop to control the color of the active tab trigger. 
Visit the [sink page ](https://themes-playground-git-ksadd-tabs-color-prop-modulz.vercel.app/sink#Tabs)to verify the colors are properly set in the examples and the default is the global accent color.
Addresses #205

tabs: Pass color prop

---

packages/radix-ui-themes/src/helpers/props/leading-trim.prop.ts

I believe this was a small bug from #235. See the classes [used in this file](https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/styles/utilities/leading-trim.css) `rt-r-lt-*`

Fix trim classname

---

apps/playground/app/sink/page.tsx
packages/radix-ui-themes/src/components/base-menu.props.ts
packages/radix-ui-themes/src/components/context-menu.props.ts
packages/radix-ui-themes/src/components/context-menu.tsx
packages/radix-ui-themes/src/components/dropdown-menu.props.ts
packages/radix-ui-themes/src/components/dropdown-menu.tsx

I've added the option to specify a color to `DropdownMenu.RadioItem`, `DropdownMenu.CheckboxItem`, `ContextMenu.RadioItem` and `ContextMenu.CheckboxItem`.
When I was using the library I found it unintuitive that you could specify a color the `DropdownMenu.Item` but not the the others. When reading the docs I thought I would be able to specify a color to these items also
I've added examples in the sink: 
None, decided to fix it myself instead of creating an issue

Add color prop to CheckboxItem and RadioItem

---

apps/playground/app/test-high-contrast/page.tsx
packages/radix-ui-themes/changelog.md
packages/radix-ui-themes/src/components/avatar.props.ts
packages/radix-ui-themes/src/components/badge.props.ts
packages/radix-ui-themes/src/components/base-tab-list.props.ts
packages/radix-ui-themes/src/components/callout.props.ts
packages/radix-ui-themes/src/components/checkbox.css
packages/radix-ui-themes/src/components/code.css
packages/radix-ui-themes/src/components/code.tsx
packages/radix-ui-themes/src/components/context-menu.tsx
packages/radix-ui-themes/src/components/dropdown-menu.tsx
packages/radix-ui-themes/src/components/em.css
packages/radix-ui-themes/src/components/heading.css
packages/radix-ui-themes/src/components/heading.props.ts
packages/radix-ui-themes/src/components/link.css
packages/radix-ui-themes/src/components/quote.css
packages/radix-ui-themes/src/components/radio-group.css
packages/radix-ui-themes/src/components/select.tsx
packages/radix-ui-themes/src/components/strong.css
packages/radix-ui-themes/src/components/text-field.props.ts
packages/radix-ui-themes/src/components/text.css
packages/radix-ui-themes/src/components/text.props.ts
packages/radix-ui-themes/src/helpers/props/color.prop.ts

- Improve how accent color and high contrast work when components are nested
- For components like Text and Heading, `--accent-12` is going to be resolved as long as there is some parent component with `data-accent-color` in the DOM that is not `.radix-themes`
- Make it so that `<Code variant="ghost">` color works just like Text, inheriting by default, but colored when an explicit `color` prop is passed
- Simplify styles for Code and Link combinations
Before:
https://themes-playground-jnjh1ct8k-modulz.vercel.app/test-high-contrast
After:
https://themes-playground-git-vlad-ghost-code-color-modulz.vercel.app/test-high-contrast

Improve how accent color and high contrast work when components are nested

---

apps/playground/app/test-textfield/page.tsx
packages/radix-ui-themes/changelog.md
packages/radix-ui-themes/src/components/alert-dialog.tsx
packages/radix-ui-themes/src/components/card.tsx
packages/radix-ui-themes/src/components/container.tsx
packages/radix-ui-themes/src/components/context-menu.tsx
packages/radix-ui-themes/src/components/data-list.tsx
packages/radix-ui-themes/src/components/dialog.tsx
packages/radix-ui-themes/src/components/dropdown-menu.tsx
packages/radix-ui-themes/src/components/em.tsx
packages/radix-ui-themes/src/components/hover-card.tsx
packages/radix-ui-themes/src/components/inset.tsx
packages/radix-ui-themes/src/components/kbd.tsx
packages/radix-ui-themes/src/components/popover.tsx
packages/radix-ui-themes/src/components/quote.tsx
packages/radix-ui-themes/src/components/radio-card-group.tsx
packages/radix-ui-themes/src/components/radio-group.tsx
packages/radix-ui-themes/src/components/scroll-area.tsx
packages/radix-ui-themes/src/components/section.tsx
packages/radix-ui-themes/src/components/select.tsx
packages/radix-ui-themes/src/components/skeleton.tsx
packages/radix-ui-themes/src/components/spinner.tsx
packages/radix-ui-themes/src/components/strong.tsx
packages/radix-ui-themes/src/components/tab-nav.tsx
packages/radix-ui-themes/src/components/table.tsx
packages/radix-ui-themes/src/components/tabs.tsx
packages/radix-ui-themes/src/components/tooltip.tsx
packages/radix-ui-themes/src/icons.tsx
packages/radix-ui-themes/src/theme-panel.tsx
packages/radix-ui-themes/src/theme.tsx

Remove native color attribute from types for components that don't support own `color` prop to avoid confusion between the two

Remove native color attribute from types

---

packages/radix-ui-themes/src/components/heading.tsx
packages/radix-ui-themes/src/components/text.tsx

Noticed that link color in callouts was not high contrast anymore due to `CalloutText` receiving an empty string color through callout context

Callout link color regression

---

apps/playground/package.json
packages/radix-ui-themes/package.json
packages/radix-ui-themes/src/helpers/get-root.tsx
yarn.lock

When testing the new version in the WorkOS monorepo I noticed a warning about `asChild={undefined}` being passed to the Card’s DOM element

Make sure `asChild` prop is not passed to DOM elements

---

apps/playground/app/sink/page.tsx
packages/radix-ui-themes/src/components/base-dialog.css

Fix a regression from https://github.com/radix-ui/themes/pull/274#discussion_r1474678336 when long dialogs would be cut off at the top without the ability to scroll (while maintaining the improvement from that PR)
See /test-dialog page for a comparison

Fix dialog scroll regression

---

apps/playground/app/demo/page.tsx
apps/playground/app/ghost-balance/page.tsx
apps/playground/app/home-os/page.tsx
apps/playground/app/sink/page.tsx
apps/playground/app/snapshot/page.tsx
apps/playground/app/test-appearance/page.tsx
apps/playground/app/test-classic-button/page.tsx
apps/playground/app/test-textfield/page.tsx
apps/playground/app/test-theme-toggle/page.tsx
apps/playground/package.json
packages/radix-ui-themes/changelog.md
packages/radix-ui-themes/src/components/index.css
packages/radix-ui-themes/src/index.ts
packages/radix-ui-themes/src/styles/tokens/color.css
packages/radix-ui-themes/src/theme-panel.css
packages/radix-ui-themes/src/theme-panel.tsx
packages/radix-ui-themes/src/theme.tsx
yarn.lock

- Set `min-height: 100vh` on the root `Theme` component
- Fix an issue when in certain situations `hasBackground` prop value would have no effect
- Refine the logic for when `Theme` has a background color by default.
- When there is no explicit `hasBackground` prop value is passed, `Theme` will display background color:
- When it is the root `Theme` component
- When it has an explicit appearance value, e.g. `<Theme apperance="light">` or `<Theme apperance="dark">`
- Body background color and is no longer set automatically. The background color is now provided by the root `Theme` by default.
- [**Breaking**] The CSS variable `--color-page-background` is no longer available. In most cases, it can be safely replaced with `--color-background` available on the `.radix-themes` element.
- …

Simplify dark theme logic

---

packages/radix-ui-themes/.eslintrc.cjs
packages/radix-ui-themes/package.json
yarn.lock

Add an ESLint plugin that makes sure all the imports in the Radix Themes package have a `.js` extension.
This is auto-fixable as well:

Require .js extension

---

apps/playground/app/sink/page.tsx
apps/playground/app/test-textfield/page.tsx
packages/radix-ui-themes/changelog.md
packages/radix-ui-themes/src/components/badge.css
packages/radix-ui-themes/src/components/base-button.css
packages/radix-ui-themes/src/components/base-menu.css
packages/radix-ui-themes/src/components/code.css
packages/radix-ui-themes/src/components/context-menu.tsx
packages/radix-ui-themes/src/components/dropdown-menu.tsx
packages/radix-ui-themes/src/components/kbd.css
packages/radix-ui-themes/src/components/progress.css
packages/radix-ui-themes/src/components/reset.css
packages/radix-ui-themes/src/components/select.css
packages/radix-ui-themes/src/components/text-area.css
packages/radix-ui-themes/src/components/text-area.tsx
packages/radix-ui-themes/src/components/text-field.css
packages/radix-ui-themes/src/components/text-field.tsx
packages/radix-ui-themes/src/styles/tokens/typography.css

- Make sure inline elements like Badge and Code that rely on padding for their height don't stretch vertically in Flex/Grid layouts, similarly to how fixed-height elements work
- Fix `a` reset regression when links would get an unintended `inline-block` style by default
- Rework Text Field and Text Area
- Make sure that the font weight is not inherited, e.g. from a wrapping `<label>` element
- Add styles for inputs of different types, like date and search
- Got rid of the internal Chrome part given [good support](https://caniuse.com/css-has) for `:has`, which simplifies greatly our implementation and allows the `style` prop to work more predictably.
- Older browser that don't support `:has` will render the disabled and autofilled styles as regular state; otherwise these components are …

Fix cosmetic bugs from RC tests

---

packages/radix-ui-themes/changelog.md
packages/radix-ui-themes/src/components/blockquote.props.ts
packages/radix-ui-themes/src/components/code.props.ts
packages/radix-ui-themes/src/components/em.props.ts
packages/radix-ui-themes/src/components/quote.props.ts
packages/radix-ui-themes/src/components/reset.tsx
packages/radix-ui-themes/src/components/slider.css
packages/radix-ui-themes/src/components/strong.props.ts
packages/radix-ui-themes/src/components/tabs.tsx

- Add `wrap` and `truncate` props to all text formatting components except `Kbd`
- Add margin props to `TabsList` and `TabsContent`
- Remove margin props from `Reset`
- Fix Slider focus outline in Safari

Add missing props

---

packages/radix-ui-themes/package.json

Adding a wildcard export so that Next.js is able to resolve direct imports from the `dist` folder
https://work-os.slack.com/archives/C066T3GNG4Q/p1708683018800289

Add a wildcard export

---

apps/playground/app/test-data-list/page.tsx
packages/radix-ui-themes/src/components/data-list.css
packages/radix-ui-themes/src/components/data-list.tsx

Covering a case when flex children with text would would not be aligned properly:

Improve Data List alignment with flexbox children

---

apps/playground/app/sink/page.tsx
packages/radix-ui-themes/changelog.md
packages/radix-ui-themes/src/components/alert-dialog.props.ts
packages/radix-ui-themes/src/components/alert-dialog.tsx
packages/radix-ui-themes/src/components/base-dialog.css
packages/radix-ui-themes/src/components/dialog.props.ts
packages/radix-ui-themes/src/components/dialog.tsx
packages/radix-ui-themes/src/components/hover-card.props.ts
packages/radix-ui-themes/src/components/hover-card.tsx
packages/radix-ui-themes/src/components/popover.props.ts
packages/radix-ui-themes/src/components/popover.tsx
packages/radix-ui-themes/src/components/segmented-control.tsx
packages/radix-ui-themes/src/components/tooltip.css
packages/radix-ui-themes/src/components/tooltip.props.ts
packages/radix-ui-themes/src/components/tooltip.tsx
packages/radix-ui-themes/src/props/height.props.ts
packages/radix-ui-themes/src/props/prop-def.ts
packages/radix-ui-themes/src/props/width.props.ts

`AlertDialog`, `Dialog`
- Add `width`, `minWidth`, `maxWidth` props to the Content part.
- Set `maxWidth="600px"` by default on the Content part.
- **[Upgrade guide]** This slightly larger than the previous `580px` value. If you use dialogs that need a different width, override `maxWidth` with your own value.
***
`Popover`, `HoverCard`
- Add `width`, `minWidth`, `maxWidth`, `height`, `minHeight`, `maxHeight` props to the Content part.
- Set `maxWidth="480px"` by default on the Content part.
- **[Upgrade guide]** If you use popovers and hover cards that need a wider width, override `maxWidth` with your own value.
***
`Tooltip`
- Add `width`, `minWidth`, `maxWidth` props.
- Set `maxWidth="200px"` by default on the tooltip content
- **[Upgrade guide]** If you use tooltips that need to be …

Add width props to portalled components

---

packages/radix-ui-themes/src/components/reset.css

Wrapping a `label` around a text field that uses `rt-reset` class would change the text field's cursor to `default` (inheriting from the label)

Fix input cursor when in `<label>`

---

packages/radix-ui-themes/src/components/segmented-control.tsx

When providing `onValueChange` to `SegmentedControl.Root`, the value would clear when interacting with the currently active element.
This is due to the handler being overridden by spreading the original `props` object, wiping out the inline conditional.
Pass `onValueChange` to `SegmentedControl.Root`.
Before:
https://github.com/radix-ui/themes/assets/11708259/b6629f6e-087d-42f4-97d8-c13414f63122
After:
https://github.com/radix-ui/themes/assets/11708259/2826721b-8895-4a13-88a2-e5e91ecf28b0

Fix `SegmentedControl` controlled behaviour

---

packages/radix-ui-themes/src/components/base-tab-list.css
packages/radix-ui-themes/src/components/base-tab-list.props.ts
packages/radix-ui-themes/src/components/container.css
packages/radix-ui-themes/src/components/container.tsx
packages/radix-ui-themes/src/components/flex.props.ts
packages/radix-ui-themes/src/components/heading.css
packages/radix-ui-themes/src/components/heading.props.ts
packages/radix-ui-themes/src/components/inset.css
packages/radix-ui-themes/src/components/link.props.ts
packages/radix-ui-themes/src/components/text-field.css

- Resolves an edge case when utility classes CSS is imported on top of custom styles and take over the custom styles unexpectedly when building on top of certain components
- Add missing box-sizing to components that have padding props on them

Minimize usage of default utility classes values

---

packages/radix-ui-themes/src/components/reset.css

Fixed an unnecessary comma causing SassError when import radix styles in main `.scss` file.
1. `@import '@radix-ui/themes/styles.css';` in main `.scss` file.
2. Run dev, will see the error: `SassError: expected selector.`
Resolved #410

:bug: Fixed an unnecessary comma causing SassError.

---

packages/radix-ui-themes/.browserslistrc
packages/radix-ui-themes/package.json
yarn.lock

Configured Autoprefixer to support browser versions from the last 2 years
This saves 17 KB of the built CSS and cleans up the web inspector experience by removing the following unnecessary transformations:
- `::-moz-placeholder`
- `::-moz-selection`
- `:-moz-any-link`
- `:-moz-read-only`
- `-moz-user-select`
- `-moz-column-gap`
- `-o-object-fit`
Examples:

Configure Autoprefixer browser support

---

packages/radix-ui-themes/src/components/avatar.props.ts
packages/radix-ui-themes/src/components/badge.props.ts
packages/radix-ui-themes/src/components/base-button.props.ts
packages/radix-ui-themes/src/components/base-menu.props.ts
packages/radix-ui-themes/src/components/blockquote.props.ts
packages/radix-ui-themes/src/components/callout.props.ts
packages/radix-ui-themes/src/components/code.props.ts
packages/radix-ui-themes/src/components/data-list.props.ts
packages/radix-ui-themes/src/components/heading.props.ts
packages/radix-ui-themes/src/components/link.props.ts
packages/radix-ui-themes/src/components/progress.props.ts
packages/radix-ui-themes/src/components/separator.props.ts
packages/radix-ui-themes/src/components/text-field.props.ts
packages/radix-ui-themes/src/components/text.props.ts
packages/radix-ui-themes/src/props/color.prop.ts

Spinning off from https://github.com/radix-ui/themes/pull/469, I found that the naming and application of color prop defs was unintuitive and took me a bit to wrap my head around after we haven't worked in this area for a bit.
This refactors color prop defs so that:
- `inheritedColorPropDef` is renamed to `colorPropDef`, which should be our default colour prop def choice. This one doesn't yield any `data-accent-color` attribute when there is no explicit value.
- The original `colorPropDef` renamed to `accentColorPropDef`. This one yields an empty `data-accent-color` attribute when there is no explicit value, which is used for coloured text-based components and when we need to indicate that nested high-contrast text should use `--accent-12`
Some components also had an unnecessary …

Rename color prop defs for clarity

---

apps/playground/app/test-high-contrast/page.tsx
packages/radix-ui-themes/changelog.md
packages/radix-ui-themes/src/components/avatar.props.ts
packages/radix-ui-themes/src/components/badge.props.ts
packages/radix-ui-themes/src/components/base-button.props.ts
packages/radix-ui-themes/src/components/base-menu.props.ts
packages/radix-ui-themes/src/components/blockquote.props.ts
packages/radix-ui-themes/src/components/callout.css
packages/radix-ui-themes/src/components/callout.props.ts
packages/radix-ui-themes/src/components/callout.tsx
packages/radix-ui-themes/src/components/code.props.ts
packages/radix-ui-themes/src/components/code.tsx
packages/radix-ui-themes/src/components/data-list.props.ts
packages/radix-ui-themes/src/components/data-list.tsx
packages/radix-ui-themes/src/components/heading.props.ts
packages/radix-ui-themes/src/components/heading.tsx
packages/radix-ui-themes/src/components/link.css
packages/radix-ui-themes/src/components/link.props.ts
packages/radix-ui-themes/src/components/progress.props.ts
packages/radix-ui-themes/src/components/separator.props.ts
packages/radix-ui-themes/src/components/text-field.props.ts
packages/radix-ui-themes/src/components/text.props.ts
packages/radix-ui-themes/src/components/text.tsx
packages/radix-ui-themes/src/props/color.prop.ts
packages/radix-ui-themes/src/styles/tokens/color.css

- Fixes a regression when links would automatically become high-contrast when that wasn't desired, e.g [WorkOS dashboard sign-in](https://dashboard.workos.com/signin):
- Fixes a regression when nested high-contrast gray text would not use the correct selection background color:
- Simplify some of the color prop mechanics

Link: Fix overzealous automatic high-contrast colour

---

packages/radix-ui-themes/changelog.md
packages/radix-ui-themes/src/components/link.css
packages/radix-ui-themes/src/components/text-area.css
packages/radix-ui-themes/src/components/text-field.css
packages/radix-ui-themes/src/components/text.css

- Rework the autofilled and disabled colors for `TextField` and `TextArea`
- Both felt a bit obnoxious when actually using apps built with them
- Tweak `Link` tap highlight style
Tap highlight before/after:

Nicer text field and text area autofill and disabled styles

---

packages/radix-ui-themes/changelog.md
packages/radix-ui-themes/src/components/progress.css
packages/radix-ui-themes/src/components/progress.tsx

Thanks for providing radix themes, it's been a joy working with this package. This is my first PR here, so please let me know if I'm missing anything.
When rendering the Progress component, calculate the transform scaleX of the Progress.Indicator using the `max` prop supplied by the user.
The `max` prop is documented for the Progress primitive component and is used when determining the `aria-valuemax` and `aria-valuetext` attributes for the Progress div.
I'm using this sample app to test the change
```javascript
import "@radix-ui/themes/styles.css";
import { useState } from "react";
import { Box, Flex, Progress, Slider, Text, Theme } from "@radix-ui/themes";
function App() {
const [value, setValue] = useState([50]);
const [max, setMax] = useState([100]);
return (
<Theme>
<div
style={{ …
```

Visually render the Progress `max` prop

---

apps/playground/app/sink/page.tsx
packages/radix-ui-themes/src/components/base-checkbox.css
packages/radix-ui-themes/src/components/checkbox.tsx
packages/radix-ui-themes/src/components/icons.tsx

This PR adds `indeterminate` state icon on a standalone checkbox. This is only possible in a controlled state so `defaultChecked` will not render.
Added to sink.
#47

chore(checkbox): add indeterminate state

---

packages/radix-ui-themes/src/components/theme.tsx

I need Radix Themes to be defined on the `<body>` element (so that, for example, the body can have a background set), and I'm providing my own implementation of `ThemeContext`. But the `ThemeContext` variable isn't exported (even though `useThemeContext` is exported), which prevents me from being able to provide a theme context on my own.
This PR exports `ThemeContext` to enable uses cases where we need to control the behavior of the theme.
N/A

Export ThemeContext

---

apps/playground/app/sink/page.tsx
packages/radix-ui-themes/src/components/segmented-control.css
packages/radix-ui-themes/src/components/segmented-control.props.ts
packages/radix-ui-themes/src/components/segmented-control.tsx

Extend `SegmentedControl` to support `disabled` functionality and style. In this implementation both `classic` and `surface` variants share the same disabled styles. [See design spec ](https://www.figma.com/design/Bdv2UWN3GrAH4qUIL7Ldnl/Launch-Week%3A-Radar?node-id=2687-22849&node-type=frame&t=S9FfI6CBMSrkXWkN-0)and [context for request](https://work-os.slack.com/archives/C066T3GNG4Q/p1729705862819629?thread_ts=1729704870.866939&cid=C066T3GNG4Q).
Visit the [sink page in the playground](https://themes-playground-git-ksadd-segmented-control-disabled-workos.vercel.app/sink#segmented-control) to see the disabled control.

Segmented control: Support `disabled` prop

---

packages/radix-ui-themes/src/components/segmented-control.css
packages/radix-ui-themes/src/components/segmented-control.tsx

This fixes two existing issues with style linting:
```
src/components/segmented-control.css
24:3  ✖  Expected "&.disabled" to have a specificity no more than "0,1,1"                                             selector-max-specificity
24:4  ✖  Expected ".disabled" to match pattern "/^((xs|sm|md|lg|xl):)?-?rt-|^radix-themes$|^(light|dark)(-theme)?$/"  selector-class-pattern
```

Fix CSS specificity issues with `SegmentedControl`

---

release-process.md

Adding some documentation on how to handle releases. Very much a WIP since this is currently manual and depends on individual access to the npm scope. Ultimately we want to set up a release workflow that runs in CI.

Add release process doc

---

packages/radix-ui-themes/changelog.md
packages/radix-ui-themes/src/components/_internal/base-dialog.css

This PR fixes the animation "flash" when closing a dialog. The root cause is a "noop" animation intended to persist the parent element's visibility long enough for its children to animate out. While the children have animations to `opacity: 0` when the dialog is closed, the opacity property itself is not set to 0. So if the child animations complete before the parent, the opacity will briefly return to its initial value. Setting the opacity to 0 fixes this.
Closes #640
https://github.com/user-attachments/assets/e78badc1-a88b-47f6-9754-d718d53a3670

dialog: Fix animation flash on close

---

packages/radix-ui-themes/changelog.md
packages/radix-ui-themes/src/components/segmented-control.tsx

`SegmentedControl.Item` duplicates its child contents, resulting in duplicate content in the accessibility tree. Adding `aria-hidden` to the inactive item to fix that.
Closes #646.

segmented-control: Prevent double screen-reader announcements

---

packages/radix-ui-themes/src/components/segmented-control.css

Fixes regression introduced in #621 where all segmented control indicators (both classic and surface variants) lost their box shadow styles. For disabled controls, there should be no box shadow on the indicator control. The CSS wasn't treating the indicator as a sibling of the item.
Visit the playground, check that both the classic and surface variant has the correct box shadow on the `::before` pseudoselecter for active controls.
- [PR introducing bug](https://github.com/radix-ui/themes/pull/621/)
- [Related issue](https://github.com/radix-ui/themes/issues/635)

Segmented control: fix indicator box shadow regression

---

packages/radix-ui-themes/esbuild-esm.mjs
packages/radix-ui-themes/package.json

With the current `sideEffects: false` declaration, webpack drops CSS files from the build completely. The line `import "@radix-ui/themes/styles.css";` does not have any effect
More details in the webpack issue: https://github.com/webpack/webpack/issues/6571
Also, the declaration need to propagate to the inner file in the `/esm` subfolder. Without that, every new package.json in a way assumes side effects by default
Patched locally, it works. 
No differences found when using Vite
A bunch PRs to other libraries with the same fix
* https://github.com/react-querybuilder/react-querybuilder/pull/763
* https://github.com/olifolkerd/tabulator/pull/3542
* https://github.com/adobe/react-spectrum/pull/707
* https://github.com/chartist-js/chartist/pull/1350

fix `sideEffects` declaration

---

apps/playground/app/test-grid-align-content/page.tsx
apps/playground/app/test-grid-align-self/page.tsx
apps/playground/app/test-grid-justify-items/page.tsx
apps/playground/app/test-grid-justify-self/page.tsx
packages/radix-ui-themes/src/components/grid.props.tsx
packages/radix-ui-themes/src/props/layout.props.ts
packages/radix-ui-themes/src/styles/utilities/align-content.css
packages/radix-ui-themes/src/styles/utilities/align-self.css
packages/radix-ui-themes/src/styles/utilities/justify-items.css
packages/radix-ui-themes/src/styles/utilities/justify-self.css
packages/radix-ui-themes/src/styles/utilities/layout.css

- Add alignContent prop to Grid component with values: start, center, end, baseline, between, around, evenly, stretch
- Add justifyItems prop to Grid component with values: start, center, end, baseline, stretch
- Add alignSelf and justifySelf props to layout system with values: start, center, end, baseline, stretch
- Create CSS utility classes for all new properties with responsive support
- Update align-self CSS to use logical values (start/end instead of flex-start/flex-end)
- Add comprehensive test pages demonstrating each new property
Added new test pages, use those for reference

Add new grid layout props: alignContent, justifyItems, alignSelf, justifySelf
