apps/playground/app/sink/page.tsx, packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/text-area.css, packages/radix-ui-themes/src/components/text-field.css
=> Rework Text Field and Text Area states

packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/base-button.css, packages/radix-ui-themes/src/components/button.css, packages/radix-ui-themes/src/components/card.css, packages/radix-ui-themes/src/components/checkbox.css, packages/radix-ui-themes/src/components/icon-button.css, packages/radix-ui-themes/src/components/radio-group.css, packages/radix-ui-themes/src/components/select.css, packages/radix-ui-themes/src/components/select.tsx, packages/radix-ui-themes/src/components/slider.css, packages/radix-ui-themes/src/components/switch.css, packages/radix-ui-themes/src/components/switch.tsx
Make sure that disabled styles correspond to the used variant
=> Improve disabled styles

packages/radix-ui-themes/package.json, packages/radix-ui-themes/postcss.config.js, yarn.lock
Discard empty rules left from combining the duplicate selectors
=> Discard empty rules

apps/playground/app/sink/page.tsx, packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/callout.css
=> Tweak Callout gaps

packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/checkbox.css, packages/radix-ui-themes/src/components/slider.css, packages/radix-ui-themes/src/components/slider.tsx, packages/radix-ui-themes/src/components/switch.css, packages/radix-ui-themes/src/components/switch.tsx
=> Fix soft and classic slider, switch look with bright colors

apps/playground/app/explore-components/page.tsx, packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/base-button.css, packages/radix-ui-themes/src/components/card.css, packages/radix-ui-themes/src/components/checkbox.css, packages/radix-ui-themes/src/components/code.css, packages/radix-ui-themes/src/components/link.css, packages/radix-ui-themes/src/components/radio-group.css, packages/radix-ui-themes/src/components/scroll-area.css, packages/radix-ui-themes/src/components/select.css, packages/radix-ui-themes/src/components/slider.css, packages/radix-ui-themes/src/components/switch.css, packages/radix-ui-themes/src/components/tabs.css, packages/radix-ui-themes/src/components/text-area.css, packages/radix-ui-themes/src/components/text-area.tsx, packages/radix-ui-themes/src/components/text-field.css, packages/radix-ui-themes/src/styles/tokens/color.css
- Update focus colors to maintain theme accent color on most gray component variants.
- Use step lighter selection color
- Use step lighter autofill color
=> Update focus and selection colors

packages/radix-ui-themes/package.json, yarn.lock
Solves https://github.com/radix-ui/themes/issues/105
=> Add missing react-use-callback-ref dep

packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/styles/animations.css
https://github.com/radix-ui/themes/assets/8441036/e4c22d1f-d942-4dd0-b5cd-fd38eb8ab4fc
=> Fix origin-aware animations

packages/radix-ui-themes/src/components/text-area.css
Update `TextArea` autofill styles to match `TextField`
=> Update `TextArea` autofill styles

packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/select.tsx
=> Fix `Select` placeholder type issue

apps/playground/app/explore-components/page.tsx, apps/playground/app/sink/page.tsx, apps/playground/app/test-skeleton/page.tsx, apps/playground/app/test-textfield/page.tsx, packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/checkbox.css, packages/radix-ui-themes/src/components/index.ts, packages/radix-ui-themes/src/components/radio-group.css, packages/radix-ui-themes/src/components/skeleton.css, packages/radix-ui-themes/src/components/skeleton.props.ts, packages/radix-ui-themes/src/components/skeleton.tsx, packages/radix-ui-themes/src/components/slider.css, packages/radix-ui-themes/src/components/switch.css, packages/radix-ui-themes/src/components/text-field.css, packages/radix-ui-themes/src/styles/index.css
=> Add Skeleton

apps/playground/app/explore-components/page.module.css, apps/playground/app/explore-components/page.tsx, apps/playground/app/sink/page.tsx, packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/package.json, packages/radix-ui-themes/src/components/index.ts, packages/radix-ui-themes/src/components/progress.css, packages/radix-ui-themes/src/components/progress.props.tsx, packages/radix-ui-themes/src/components/progress.tsx, packages/radix-ui-themes/src/components/slider.css, packages/radix-ui-themes/src/styles/index.css, yarn.lock
@vladmoroz you might want to fine-tune sizes / variants / radius.
It's mostly a mix of WorkDS `Progress` and Radix Themes `Slider`.
https://github.com/radix-ui/themes/assets/1539897/fefaf577-fd9f-4c16-8ecc-7f1b58a9a409
=> Add Progress

apps/playground/app/explore-components/page.tsx, apps/playground/app/sink/page.tsx, apps/playground/app/test-textfield/page.tsx, packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/index.ts, packages/radix-ui-themes/src/components/spinner.css, packages/radix-ui-themes/src/components/spinner.props.ts, packages/radix-ui-themes/src/components/spinner.tsx, packages/radix-ui-themes/src/styles/index.css
=> Add Spinner

apps/playground/app/explore-components/page.tsx, apps/playground/app/sink/page.tsx, apps/playground/components/loading-buttons.tsx, packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/base-button.css, packages/radix-ui-themes/src/components/base-button.props.ts, packages/radix-ui-themes/src/components/base-button.tsx, packages/radix-ui-themes/src/components/callout.tsx, packages/radix-ui-themes/src/components/skeleton.props.ts, packages/radix-ui-themes/src/components/spinner.css, packages/radix-ui-themes/src/components/spinner.props.ts, packages/radix-ui-themes/src/components/spinner.tsx, packages/radix-ui-themes/src/helpers/props/index.ts, packages/radix-ui-themes/src/helpers/props/map-prop-values.ts
https://github.com/radix-ui/themes/assets/1539897/4da34d85-3086-4366-875d-721a399c0037
=> Add loading to `Spinner`, `IconButton` and `Button`

packages/radix-ui-themes/README.md
The README is missing from the [npm page](https://www.npmjs.com/package/@radix-ui/themes), this copies over the README in the repository root to the package root.
=> Add README to pckg root

apps/playground/app/sink/page.tsx, packages/radix-ui-themes/src/components/base-tab-list.css, packages/radix-ui-themes/src/components/base-tab-list.props.ts
Closes https://github.com/radix-ui/themes/issues/181
=> Add justify and wrap props to Tabs

apps/playground/app/test-text-wrap/page.tsx, packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/heading.props.ts, packages/radix-ui-themes/src/components/link.props.ts, packages/radix-ui-themes/src/components/text.props.ts, packages/radix-ui-themes/src/helpers/extract-props.ts, packages/radix-ui-themes/src/helpers/props/index.ts, packages/radix-ui-themes/src/helpers/props/text-wrap.prop.ts, packages/radix-ui-themes/src/helpers/props/truncate.prop.ts, packages/radix-ui-themes/src/styles/index.css, packages/radix-ui-themes/src/styles/utilities/text-wrap.css, packages/radix-ui-themes/src/styles/utilities/truncate.css
- Add new `wrap` text prop corresponding to the `text-wrap` CSS property
- Add new `truncate` text prop
- Update changelog
=> Add text `wrap` and `truncate` props

apps/playground/app/sink/page.tsx, apps/playground/app/test-radio-card/page.tsx, packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/index.ts, packages/radix-ui-themes/src/components/radio-card-group.css, packages/radix-ui-themes/src/components/radio-card-group.props.ts, packages/radix-ui-themes/src/components/radio-card-group.tsx, packages/radix-ui-themes/src/components/radio-group.tsx, packages/radix-ui-themes/src/styles/index.css
https://github.com/radix-ui/themes/assets/1539897/58bc344f-5d5f-467e-985e-79605dfaa8e9
=> Add RadioCardGroup

apps/playground/app/test-dialog/page.tsx, packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/alert-dialog.css, packages/radix-ui-themes/src/components/alert-dialog.tsx, packages/radix-ui-themes/src/components/dialog.css, packages/radix-ui-themes/src/components/dialog.tsx
See the [test-dialog](https://themes-playground-git-vlad-dialog-scroll-modulz.vercel.app/test-dialog) page
Before
https://github.com/radix-ui/themes/assets/8441036/f142a81b-295a-4776-80b6-164a17b14a53
After
https://github.com/radix-ui/themes/assets/8441036/037bd2eb-caed-4743-ab97-d3207ae8573e
=> Confine dialog scroll to viewport

apps/playground/app/sink/page.tsx, packages/radix-ui-themes/src/components/card.css, packages/radix-ui-themes/src/components/code.css, packages/radix-ui-themes/src/components/kbd.css, packages/radix-ui-themes/src/components/kbd.props.ts, packages/radix-ui-themes/src/components/kbd.tsx
Something we had to hack together on the spot in the WorkOS docs here
=> Add interactive Kbd styles

packages/radix-ui-themes/src/components/code.css, packages/radix-ui-themes/src/components/radio-card-group.css, packages/radix-ui-themes/src/helpers/props/text-align.prop.ts
Did an RC to test and found these issues
=> RC release CSS fixes

packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/base-button.css, packages/radix-ui-themes/src/components/base-tab-list.css, packages/radix-ui-themes/src/components/card.css, packages/radix-ui-themes/src/components/checkbox-card-group.css, packages/radix-ui-themes/src/components/checkbox.css, packages/radix-ui-themes/src/components/kbd.css, packages/radix-ui-themes/src/components/link.css, packages/radix-ui-themes/src/components/radio-card-group.css, packages/radix-ui-themes/src/components/radio-group.css, packages/radix-ui-themes/src/components/scroll-area.css, packages/radix-ui-themes/src/components/select.css, packages/radix-ui-themes/src/components/slider.css, packages/radix-ui-themes/src/components/switch.css, packages/radix-ui-themes/src/components/tabs.css, packages/radix-ui-themes/src/components/text-area.css, packages/radix-ui-themes/src/components/text-field.css, packages/radix-ui-themes/src/styles/tokens/color.css
Realised we had already solved this problem in the theme panel component
https://github.com/radix-ui/themes/assets/8441036/d1c253f3-de54-46ba-92e3-e0d14198e07d
=> Improve Radio Card focus states

packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/animations.css, packages/radix-ui-themes/src/components/base-dialog.css, packages/radix-ui-themes/src/components/scroll-area.css, packages/radix-ui-themes/src/components/tooltip.css
https://github.com/radix-ui/themes/discussions/289
=> Speed up animations

.prettierrc, apps/playground/app/sink/page.tsx, packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/package.json, packages/radix-ui-themes/src/components/index.css, packages/radix-ui-themes/src/components/index.ts, packages/radix-ui-themes/src/components/segmented-control.css, packages/radix-ui-themes/src/components/segmented-control.parts.ts, packages/radix-ui-themes/src/components/segmented-control.props.ts, packages/radix-ui-themes/src/components/segmented-control.tsx, packages/radix-ui-themes/src/props/index.ts, yarn.lock
=> Add Segmented Control

packages/radix-ui-themes/src/components/skeleton.tsx, packages/radix-ui-themes/src/components/spinner.tsx
https://work-os.slack.com/archives/C066T3GNG4Q/p1708517054450349
=> Spinner, Skeleton: Return children directly

packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/base-card.css, packages/radix-ui-themes/src/components/card.css, packages/radix-ui-themes/src/components/segmented-control.css, packages/radix-ui-themes/src/styles/tokens/shadow.css
- Refine classic card shadows
- Tweak ghost card background when focused
- Tweak Segmented Control shadow
Based on the battle-tested values:
https://github.com/workos/workos/blob/main/packages/design-system/theme.css#L15-L21
=> Refine classic card shadows

packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/select.css, packages/radix-ui-themes/src/components/select.tsx
Update the disabled trigger text color so it’s easier to read, similarly to Text Field
=> Update disabled select colors

apps/playground/app/test-data-list/page.tsx, packages/radix-ui-themes/src/components/data-list.css
- Ensure baseline alignment for label when nesting a Flex inside
- Add NextThemeProvider to the Data List test page
=> Data List: Ensure baseline alignment for label

packages/radix-ui-themes/src/components/scroll-area.css
Fixes an issue when overscroll would be overzealously prevented on vertical scroll areas
=> ScrollArea: Improve `overscroll-behavior-x`

packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/slider.css
- Fixes an issue when Slider would grow in a flex container overzealously
- Makes it so that vertical Slider fills container height when possible
=> Slider: Improve layout defaults

apps/playground/app/sink/page.tsx, packages/radix-ui-themes/src/props/color.prop.ts
Not used outside of the playground
=> Remove `accentColorsGrouped` export

apps/playground/app/test-high-contrast/page.tsx, packages/radix-ui-themes/src/components/link.css, packages/radix-ui-themes/src/components/link.tsx
Test pages (search for "All inline components with high contrast"):
Before
https://themes-playground-gguky9e4j-modulz.vercel.app/test-high-contrast
After
https://themes-playground-gumetrpj3-modulz.vercel.app/test-high-contrast
=> Link: Fix `highContrast` prop without an explicit `color`

packages/radix-ui-themes/src/components/box.tsx, packages/radix-ui-themes/src/components/flex.tsx, packages/radix-ui-themes/src/components/grid.tsx, packages/radix-ui-themes/src/components/heading.tsx, packages/radix-ui-themes/src/components/text.tsx, packages/radix-ui-themes/src/helpers/index.ts, packages/radix-ui-themes/src/helpers/nice-intersection.ts
Relax polymorphic types to make extending components easier
https://work-os.slack.com/archives/C066T3GNG4Q/p1710869863537029
=> Relax polymorphic types

packages/radix-ui-themes/changelog.md
A few tweaks I made before/during adding the release to the website
=> Changelog tweaks

packages/radix-ui-themes/src/components/inset.css
https://github.com/radix-ui/themes/assets/8441036/473d1669-1c0f-4619-9713-fb177583edca
=> Inset: Fix responsive sides

apps/playground/app/test-webkit-tap-highlight-color/page.tsx, packages/radix-ui-themes/src/components/base-button.css, packages/radix-ui-themes/src/components/card.css, packages/radix-ui-themes/src/components/checkbox-cards.css, packages/radix-ui-themes/src/components/link.css, packages/radix-ui-themes/src/components/reset.css, packages/radix-ui-themes/src/components/text.css
Added tap highlight styles where they felt necessary
https://github.com/radix-ui/themes/assets/8441036/a688ca12-7951-429e-b0db-0ee5d1d36be1
=> Add tap highlight styles

packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/package.json, packages/radix-ui-themes/src/components/base-checkbox.css, packages/radix-ui-themes/src/components/base-radio.css, packages/radix-ui-themes/src/components/checkbox-group.css, packages/radix-ui-themes/src/components/checkbox.css
=> Fix Radio and Checkbox cursors in Safari

packages/radix-ui-themes/src/components/link.css
=> Recover hover styles for Link when rendered as button

packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/spinner.css
Add `--spinner-animation-duration` CSS variable as an escape hatch to customise the spinner animation speed
=> Add `--spinner-animation-duration` CSS variable

packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/package.json, packages/radix-ui-themes/src/styles/tokens/index.css
https://work-os.slack.com/archives/C03B7T7T0HE/p1714149312229179
=> 3.0.3: Fix explicit appearance grays

apps/playground/app/test-dialog/page.tsx, packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/src/components/alert-dialog.tsx, packages/radix-ui-themes/src/components/base-dialog.css, packages/radix-ui-themes/src/components/dialog.props.ts, packages/radix-ui-themes/src/components/dialog.tsx
See https://themes-playground-git-vlad-dialog-align-workos.vercel.app/test-dialog
=> Add `align`, `height`, `minHeight`, and `maxHeight`  dialog props

packages/radix-ui-themes/src/components/popover.tsx, yarn.lock
Expose the Popover.Anchor part
=> feature: Expose Popopver.Anchor part

packages/radix-ui-themes/changelog.md, packages/radix-ui-themes/package.json
Update changelog and package.json version to include following changes:
- Export `ThemeContext` see [#582](https://github.com/radix-ui/themes/pull/582)
- Export `Popover.Anchor` see [#588](https://github.com/radix-ui/themes/pull/588)
=> Release 3.1.4
